spring:
  datasource:
    url: jdbc:mysql://localhost:3306/CNExpenses?createDatabaseIfNotExist=true
    username: root
    password: Deep@0801
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update